[template]
src = "dynamic-routing.cfg.tmpl"
dest = "/haproxy.d/50-dynamic-routing.cfg"
keys = [
  "/stacks",
]
check_cmd = "haproxy -c -f /haproxy.d/"
reload_cmd = "/usr/local/sbin/haproxy-reload.sh"
